### PR TITLE
Set new version ast

### PR DESCRIPTION
**Pull request by simanna**
For install new version wata727-pahout We have to add updated version ast-extension

### CODE REVIEW

**Review by EvgenyOrekhov — COMMENTED** [review]
0.1.7 is too old.

I can see here that wata727/pahout works with ext-ast ^1.0.0: https://github.com/wata727/pahout/blob/0.7.0/composer.json#L18

Have you tried the latest version (1.0.5)?

BTW, which version of ast does pecl install if you don't specify a version?

**Comment by simanna** [comment]
When I tried to install this version - 1.0.5, I had some problems with updating phan. So i decided to set this old version. But I'll try to update phan.

**Comment by simanna** [comment]
Not problems with wata727/pahout., we have a problem with phan. It isn't constant 'ast\AST_COALESCE'

**Comment by EvgenyOrekhov** [comment]
Sounds like a plan. I'd say it's better to upgrade several dependencies than to downgrade one.

FYI, the latest phan needs ast 1.0.1+: https://github.com/phan/phan/blob/2.4.4/composer.json#L39.

**Comment by EvgenyOrekhov** [comment]
I tried building the Dockerfile from the master branch, pecl uses the latest ast:

```text
downloading ast-1.0.5.tgz ...
Starting to download ast-1.0.5.tgz (40,582 bytes)
...........done: 40,582 bytes

...

Successfully built 3bae0d63fce9
```

So this change that you've submitted is not needed. You just need to log into https://hub.docker.com/ and manually trigger an image build.

If that helps, please close this PR.

**Comment by simanna** [comment]
@EvgenyOrekhov  You're right. Thank you very much)

**Pull request closed without merging**
